web/config/routes.rb
Rails.application.routes.draw do
  resources :leads
  
  root 'leads#index'
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web/app/models/lead.rb
class Lead < ApplicationRecord
  before_save :normalize_phone

  validates :name, presence: true
  validates :email, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP  } 
  validates :phone, phone: true, allow_blank: false

  def parsed_phone
    parsed_phone = Phonelib.parse(phone)
    return phone if parsed_phone.invalid?

    parsed_phone
  end

  def formatted_phone(formatted=true)
    return phone unless parsed_phone.respond_to?(:country_code)

    formatted =
      if parsed_phone.country_code == "1"
        parsed_phone.national formatted
      else
        parsed_phone.full_international formatted
      end
    formatted.gsub!(";", " x")
    formatted
  end

  private

  def normalize_phone
    self.phone = Phonelib.parse(phone).full_e164.presence
  end
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

web/app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: %i[ show edit update destroy ]

  # GET /leads or /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1 or /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads or /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: "Lead was successfully created." }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1 or /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: "Lead was successfully updated." }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1 or /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: "Lead was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lead_params
      params.require(:lead).permit(:ga_client_id, :name, :phone, :email)
    end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/leads_helper.rb
module LeadsHelper
end

web/app/views/layouts/_ga.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YFQDMRN5KF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-YFQDMRN5KF');
</script>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= render "layouts/ga" %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

web/app/views/leads/_form.html.erb
<%= form_with(model: lead) do |form| %>
  <% if lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
        <% lead.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, 
      placeholder: 'John Smith', required: true %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, value: @lead&.formatted_phone(false), 
      placeholder: '2125550000', required: true %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, 
      placeholder: 'j.smith@example.com', required: true %>
  </div>

  <%= form.hidden_field :ga_client_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

web/app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

web/app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leads</h1>

<table>
  <thead>
    <tr>
      <th>Ga client</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.ga_client_id %></td>
        <td><%= lead.name %></td>
        <td><%= lead.formatted_phone %></td>
        <td><%= lead.email %></td>
        <td><%= link_to 'Show', lead %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lead', new_lead_path %>

web/app/views/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Back', leads_path %>

<%= javascript_pack_tag 'new_lead' %>

web/app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ga client:</strong>
  <%= @lead.ga_client_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @lead.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lead.formatted_phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>